<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChoiceTestAnswerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('choice_test_answer')->insert(['question_id' => '1','value' => '1','answer' => 'Memajukan Kalimantan Membangun Indonesia']);
        DB::table('choice_test_answer')->insert(['question_id' => '1','value' => '0','answer' => 'Mengabdi Untuk Kesejahteraan Bersama']);
        DB::table('choice_test_answer')->insert(['question_id' => '1','value' => '0','answer' => 'Menjadi The True Regional Champion']);
        DB::table('choice_test_answer')->insert(['question_id' => '1','value' => '0','answer' => 'Maju lebih cepat tumbuh lebih kuat']);
        DB::table('choice_test_answer')->insert(['question_id' => '2','value' => '1','answer' => 'Kreatif dalam mengembangkan produk dan layanan perbankan']);
        DB::table('choice_test_answer')->insert(['question_id' => '2','value' => '0','answer' => 'Meletakkan karakter sebagai basis pengembangan reputasi, baik institusi maupun perorangan']);
        DB::table('choice_test_answer')->insert(['question_id' => '2','value' => '0','answer' => 'Mengembangkan bisnis dan layanan perbankan yang berorientasi solusi dan berbasis teknologi.']);
        DB::table('choice_test_answer')->insert(['question_id' => '2','value' => '0','answer' => 'Membudayakan filosofi kerja yang berorientasi pada prestasi.']);
        DB::table('choice_test_answer')->insert(['question_id' => '3','value' => '1','answer' => '14 Oktober 1965']);
        DB::table('choice_test_answer')->insert(['question_id' => '3','value' => '0','answer' => '14 Oktober 1955']);
        DB::table('choice_test_answer')->insert(['question_id' => '3','value' => '0','answer' => '14 Oktober 1966']);
        DB::table('choice_test_answer')->insert(['question_id' => '3','value' => '0','answer' => '14 Oktober 1964']);
        DB::table('choice_test_answer')->insert(['question_id' => '4','value' => '1','answer' => 'terdiri dari huruf besar/kapital, huruf kecil, angka dan karakter spesial dengan minimal 8 karakter spesial dengan minimal 8 karakter ']);
        DB::table('choice_test_answer')->insert(['question_id' => '4','value' => '0','answer' => 'terdiri dari , huruf kecil, angka dan karakter spesial dengan minimal 8 karakter spesial dengan minimal 8 karakter ']);
        DB::table('choice_test_answer')->insert(['question_id' => '4','value' => '0','answer' => 'terdiri huruf dan angka minimal 6 karakter dan maksimal 14 karakter']);
        DB::table('choice_test_answer')->insert(['question_id' => '4','value' => '0','answer' => 'terdiri huruf kapital, huruf kecil dan angka minimal 8 karakter dan maksimal 14 karakter']);
        DB::table('choice_test_answer')->insert(['question_id' => '5','value' => '1','answer' => 'Giro Perorangan']);
        DB::table('choice_test_answer')->insert(['question_id' => '5','value' => '0','answer' => 'Giro Pemerintah']);
        DB::table('choice_test_answer')->insert(['question_id' => '5','value' => '0','answer' => 'Giro Perusahaan']);
        DB::table('choice_test_answer')->insert(['question_id' => '5','value' => '0','answer' => 'Giro Organisasi Perangkat Daerah']);
        DB::table('choice_test_answer')->insert(['question_id' => '6','value' => '1','answer' => 'Menjadikan kepentingan nasabah sebagai dasar setiap kegiatan bisnis']);
        DB::table('choice_test_answer')->insert(['question_id' => '6','value' => '0','answer' => 'Menjadi pendukung utama program pembangunan ekonomi dan menopang pemberdayaan perekonomian rakyat.']);
        DB::table('choice_test_answer')->insert(['question_id' => '6','value' => '0','answer' => 'Membudayakan filosofi kerja yang berorientasi pada prestasi.']);
        DB::table('choice_test_answer')->insert(['question_id' => '6','value' => '0','answer' => 'Menjaga dan meningkatkan reputasi Bank.']);
        DB::table('choice_test_answer')->insert(['question_id' => '7','value' => '1','answer' => 'Penggantian Kartu ATM karena hilang boleh dikuasakan. ']);
        DB::table('choice_test_answer')->insert(['question_id' => '7','value' => '0','answer' => 'Nasabah wajib membuat Surat Pernyataan Kehilangan Kartu ATM yang dilengkapi materai dan membebaskan bank dari tuntutan dikemudian hari atas kehilangan Kartu dimaksud. ']);
        DB::table('choice_test_answer')->insert(['question_id' => '7','value' => '0','answer' => 'Nasabah wajib mengisi aplikasi permohonan penggantian kartu ATM karena hilang. ']);
        DB::table('choice_test_answer')->insert(['question_id' => '7','value' => '0','answer' => 'Nasabah harus menunjukan asli identitas dan buku Tabungan serta mengingat transaksi terakhir.  ']);
        DB::table('choice_test_answer')->insert(['question_id' => '8','value' => '1','answer' => 'Rp. 11.000,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '8','value' => '0','answer' => 'Rp. 8.500,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '8','value' => '0','answer' => 'Rp. 3.500,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '8','value' => '0','answer' => 'Rp. 6.000,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '9','value' => '1','answer' => 'Rp. 100.000,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '9','value' => '0','answer' => 'Rp. 1.000.000,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '9','value' => '0','answer' => 'Rp. 500.000,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '9','value' => '0','answer' => 'Rp. 2.500.000,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '10','value' => '1','answer' => 'Password dan PIN']);
        DB::table('choice_test_answer')->insert(['question_id' => '10','value' => '0','answer' => 'Sidik Jari, Password dan PIN']);
        DB::table('choice_test_answer')->insert(['question_id' => '10','value' => '0','answer' => 'Sidik Jari dan PIN']);
        DB::table('choice_test_answer')->insert(['question_id' => '10','value' => '0','answer' => 'User ID, Password dan PIN']);
        DB::table('choice_test_answer')->insert(['question_id' => '11','value' => '1','answer' => 'Giro Perorangan']);
        DB::table('choice_test_answer')->insert(['question_id' => '11','value' => '0','answer' => 'Giro Pemerintah']);
        DB::table('choice_test_answer')->insert(['question_id' => '11','value' => '0','answer' => 'Giro Perusahaan']);
        DB::table('choice_test_answer')->insert(['question_id' => '11','value' => '0','answer' => 'Giro Organisasi Perangkat Daerah']);
        DB::table('choice_test_answer')->insert(['question_id' => '12','value' => '1','answer' => 'USD']);
        DB::table('choice_test_answer')->insert(['question_id' => '12','value' => '0','answer' => 'YEN']);
        DB::table('choice_test_answer')->insert(['question_id' => '12','value' => '0','answer' => 'SAR']);
        DB::table('choice_test_answer')->insert(['question_id' => '12','value' => '0','answer' => 'SGD']);
        DB::table('choice_test_answer')->insert(['question_id' => '13','value' => '1','answer' => 'Menyerahkan formulir dengan posisi menghadap nasabah  dengan kedua tangan, tidak disorongkan ke nasabah. Menunjukkan dan menjelaskan field yang harus diisi nasabah dengan lima jari merapat, posisi telapak tangan menghadap ke atas.']);
        DB::table('choice_test_answer')->insert(['question_id' => '13','value' => '0','answer' => 'Menyerahkan formulir dengan menghadap nasabah, diserahkan satu tangan dan tidak boleh  disorongkan ke nasabah. Menunjukkan dan menjelaskan field yang harus diisi nasabah dengan telunjuk jari.']);
        DB::table('choice_test_answer')->insert(['question_id' => '13','value' => '0','answer' => 'Menyerahkan formulir dengan posisi menghadap nasabah  dengan kedua tangan, tidak disorongkan ke nasabah. Menunjukkan dan menjelaskan field yang harus diisi nasabah dengan dengan telunjuk jari..']);
        DB::table('choice_test_answer')->insert(['question_id' => '13','value' => '0','answer' => 'Menyerahkan formulir dengan posisi menghadap nasabah  dengan kedua tangan, tidak disorongkan ke nasabah.  Menunjukkan dan menjelaskan field yang harus diisi nasabah dengan lima jari merapat, posisi telapak tangan menghadap ke atas.']);
        DB::table('choice_test_answer')->insert(['question_id' => '14','value' => '1','answer' => '30 (tiga) puluh hari']);
        DB::table('choice_test_answer')->insert(['question_id' => '14','value' => '0','answer' => '10 (sepuluh) hari']);
        DB::table('choice_test_answer')->insert(['question_id' => '14','value' => '0','answer' => '7 (tujuh) hari']);
        DB::table('choice_test_answer')->insert(['question_id' => '14','value' => '0','answer' => 'Dapat langsung diimplementasikan']);
        DB::table('choice_test_answer')->insert(['question_id' => '15','value' => '1','answer' => 'Dalam hal fisik Uang Rupiah Kertas terlipat']);
        DB::table('choice_test_answer')->insert(['question_id' => '15','value' => '0','answer' => 'Dalam hal fisik Uang Rupiah Kertas lebih besar dari 2/3 ukuran aslinya termasuk di dalam Uang Rupiah Kertas Rusak']);
        DB::table('choice_test_answer')->insert(['question_id' => '15','value' => '0','answer' => 'Dalam hal fisik Uang Rupiah Logam lebih besar dar 1/2 ukuran aslinya termasuk di dalam Uang Rupiah Logam Rusak']);
        DB::table('choice_test_answer')->insert(['question_id' => '15','value' => '0','answer' => 'Dalam hal fisik Uang Rupiah Kertas mengerut termasuk di dalam Uang Rupiah cacat/lusuh']);
        DB::table('choice_test_answer')->insert(['question_id' => '16','value' => '1','answer' => 'Rp. 10.000.000,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '16','value' => '0','answer' => 'Rp. 5.000.000,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '16','value' => '0','answer' => 'Rp. 7.500.000,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '16','value' => '0','answer' => 'Rp. 15.000.000']);
        DB::table('choice_test_answer')->insert(['question_id' => '17','value' => '1','answer' => 'Rp. 5.000/ bulan']);
        DB::table('choice_test_answer')->insert(['question_id' => '17','value' => '0','answer' => 'Rp. 0,-/bulan']);
        DB::table('choice_test_answer')->insert(['question_id' => '17','value' => '0','answer' => 'Rp. 2.500/bulan']);
        DB::table('choice_test_answer')->insert(['question_id' => '17','value' => '0','answer' => 'Rp. 10.000/bulan']);
        DB::table('choice_test_answer')->insert(['question_id' => '18','value' => '1','answer' => 'buku tabungan dan kartu identitas asli']);
        DB::table('choice_test_answer')->insert(['question_id' => '18','value' => '0','answer' => 'buku tabungan, Kartu ATM dan fotocopy kartu identitas']);
        DB::table('choice_test_answer')->insert(['question_id' => '18','value' => '0','answer' => 'buku tabungan dan kartu identitas asli, selanjutnya teller memfotokopi untuk dilampirkan pada slip transaksi']);
        DB::table('choice_test_answer')->insert(['question_id' => '18','value' => '0','answer' => 'buku tabungan, Kartu ATM dan kartu identitas asli']);
        DB::table('choice_test_answer')->insert(['question_id' => '19','value' => '1','answer' => 'Rp. 2.500.000,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '19','value' => '0','answer' => 'Rp. 1.000.000,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '19','value' => '0','answer' => 'Rp.500.000,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '19','value' => '0','answer' => 'Rp. 100.000']);
        DB::table('choice_test_answer')->insert(['question_id' => '20','value' => '1','answer' => '1500124']);
        DB::table('choice_test_answer')->insert(['question_id' => '20','value' => '0','answer' => '1500241']);
        DB::table('choice_test_answer')->insert(['question_id' => '20','value' => '0','answer' => '1500142']);
        DB::table('choice_test_answer')->insert(['question_id' => '20','value' => '0','answer' => '1500421']);
        DB::table('choice_test_answer')->insert(['question_id' => '21','value' => '1','answer' => 'Rp. 4.000,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '21','value' => '0','answer' => 'Rp. 2.500,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '21','value' => '0','answer' => 'Rp. 5.000,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '21','value' => '0','answer' => 'Rp 6.500,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '22','value' => '1','answer' => 'Sepatu']);
        DB::table('choice_test_answer')->insert(['question_id' => '22','value' => '0','answer' => 'Sikap mengawali']);
        DB::table('choice_test_answer')->insert(['question_id' => '22','value' => '0','answer' => 'Sikap Mengakhiri Layanan ']);
        DB::table('choice_test_answer')->insert(['question_id' => '22','value' => '0','answer' => 'Pembukaan Rekening Tabungan ']);
        DB::table('choice_test_answer')->insert(['question_id' => '23','value' => '1','answer' => 'Tersangka TPPU']);
        DB::table('choice_test_answer')->insert(['question_id' => '23','value' => '0','answer' => 'Koruptor']);
        DB::table('choice_test_answer')->insert(['question_id' => '23','value' => '0','answer' => 'Telah meninggal dunia']);
        DB::table('choice_test_answer')->insert(['question_id' => '23','value' => '0','answer' => 'tidak dketahui keberadaannya']);
        DB::table('choice_test_answer')->insert(['question_id' => '24','value' => '1','answer' => 'Prinsip Mengenal Nasabah']);
        DB::table('choice_test_answer')->insert(['question_id' => '24','value' => '0','answer' => 'Prinsip 3 Pilar']);
        DB::table('choice_test_answer')->insert(['question_id' => '24','value' => '0','answer' => 'Prinsip Kehati-hatian']);
        DB::table('choice_test_answer')->insert(['question_id' => '24','value' => '0','answer' => 'Prinsip Kepatuhan']);
        DB::table('choice_test_answer')->insert(['question_id' => '25','value' => '1','answer' => 'PPATK']);
        DB::table('choice_test_answer')->insert(['question_id' => '25','value' => '0','answer' => 'OJK']);
        DB::table('choice_test_answer')->insert(['question_id' => '25','value' => '0','answer' => 'BI']);
        DB::table('choice_test_answer')->insert(['question_id' => '25','value' => '0','answer' => 'Kepolisian']);
        DB::table('choice_test_answer')->insert(['question_id' => '26','value' => '1','answer' => 'Menjadikan kepentingan nasabah sebagai dasar setiap kegiatan bisnis']);
        DB::table('choice_test_answer')->insert(['question_id' => '26','value' => '0','answer' => 'Mempunyai rasa tanggung jawab yang tinggi sebagai warga korporasi yang baik']);
        DB::table('choice_test_answer')->insert(['question_id' => '26','value' => '0','answer' => 'Meletakkan karakter sebagai basis pengembangan reputasi, baik institusi maupun perorangan']);
        DB::table('choice_test_answer')->insert(['question_id' => '26','value' => '0','answer' => 'Mempunyai semangat juang untuk selalu menjadi juara']);
        DB::table('choice_test_answer')->insert(['question_id' => '27','value' => '1','answer' => 'wajib menolak membukakan rekening']);
        DB::table('choice_test_answer')->insert(['question_id' => '27','value' => '0','answer' => 'berhak menolak membukakan rekening']);
        DB::table('choice_test_answer')->insert(['question_id' => '27','value' => '0','answer' => 'boleh membukakan rekening']);
        DB::table('choice_test_answer')->insert(['question_id' => '27','value' => '0','answer' => 'wajib membukakan rekening']);
        DB::table('choice_test_answer')->insert(['question_id' => '28','value' => '1','answer' => '20.000.000,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '28','value' => '0','answer' => '30.000.000,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '28','value' => '0','answer' => '15.000.000,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '28','value' => '0','answer' => '2.500.000,-']);
        DB::table('choice_test_answer')->insert(['question_id' => '29','value' => '1','answer' => 'Semua Jawaban Benar']);
        DB::table('choice_test_answer')->insert(['question_id' => '29','value' => '0','answer' => 'Menggunakan CIF wali']);
        DB::table('choice_test_answer')->insert(['question_id' => '29','value' => '0','answer' => 'Penamaan pada buku tabungan menggunakan nama wali QQ nama anak']);
        DB::table('choice_test_answer')->insert(['question_id' => '29','value' => '0','answer' => 'KTP-el orang tua, Kartu Keluarga & Akte Kelahiran']);
        DB::table('choice_test_answer')->insert(['question_id' => '30','value' => '1','answer' => '60 Hari Kalender']);
        DB::table('choice_test_answer')->insert(['question_id' => '30','value' => '0','answer' => '180 Hari Kalender']);
        DB::table('choice_test_answer')->insert(['question_id' => '30','value' => '0','answer' => '14 Hari Kerja']);
        DB::table('choice_test_answer')->insert(['question_id' => '30','value' => '0','answer' => '7 Hari Kerja']);
        DB::table('choice_test_answer')->insert(['question_id' => '31','value' => '0','answer' => 'Membantu dan Menolong']);
        DB::table('choice_test_answer')->insert(['question_id' => '31','value' => '0','answer' => 'Memenuhi Kebutuhan Customer']);
        DB::table('choice_test_answer')->insert(['question_id' => '31','value' => '0','answer' => 'Melampaui Harapan Customer']);
        DB::table('choice_test_answer')->insert(['question_id' => '31','value' => '1','answer' => 'Melayani dengan Ketulusan']);
        DB::table('choice_test_answer')->insert(['question_id' => '32','value' => '1','answer' => 'Up Selling']);
        DB::table('choice_test_answer')->insert(['question_id' => '32','value' => '0','answer' => 'Add On']);
        DB::table('choice_test_answer')->insert(['question_id' => '32','value' => '0','answer' => 'Cross Selling']);
        DB::table('choice_test_answer')->insert(['question_id' => '32','value' => '0','answer' => 'Migration']);
        DB::table('choice_test_answer')->insert(['question_id' => '33','value' => '1','answer' => 'Financial Advisory']);
        DB::table('choice_test_answer')->insert(['question_id' => '33','value' => '0','answer' => 'Proteksi Keuangan']);
        DB::table('choice_test_answer')->insert(['question_id' => '33','value' => '0','answer' => 'Counseling Financial']);
        DB::table('choice_test_answer')->insert(['question_id' => '33','value' => '0','answer' => 'Customer Segmentation']);
        DB::table('choice_test_answer')->insert(['question_id' => '34','value' => '1','answer' => 'Wellingness to help']);
        DB::table('choice_test_answer')->insert(['question_id' => '34','value' => '0','answer' => 'Move Away']);
        DB::table('choice_test_answer')->insert(['question_id' => '34','value' => '0','answer' => 'Product Defect']);
        DB::table('choice_test_answer')->insert(['question_id' => '34','value' => '0','answer' => 'Bad Attitude']);
        DB::table('choice_test_answer')->insert(['question_id' => '35','value' => '1','answer' => 'Kenali Nasabah – Lakukan Pendekatan – Analisa Kebutuhan – Tawarkan Solusi – Atasi Keberatan – Sepakati Solusi ']);
        DB::table('choice_test_answer')->insert(['question_id' => '35','value' => '0','answer' => 'Kenali Nasabah – Analisa Kebutuhan – Tawarkan Solusi – Atasi Keberatan']);
        DB::table('choice_test_answer')->insert(['question_id' => '35','value' => '0','answer' => 'Kenali Nasabah – Lakukan Pendekatan – Tawarkan Solusi – Sepakati Solusi']);
        DB::table('choice_test_answer')->insert(['question_id' => '35','value' => '0','answer' => 'Kenali Nasabah – Analisa Kebutuhan – Tawarkan Solusi – Lakukan Pendekatan – Atasi Keberatan – Sepakati Solusi']);
        DB::table('choice_test_answer')->insert(['question_id' => '36','value' => '0','answer' => 'Visual']);
        DB::table('choice_test_answer')->insert(['question_id' => '36','value' => '0','answer' => 'Verbal']);
        DB::table('choice_test_answer')->insert(['question_id' => '36','value' => '0','answer' => 'Vocal']);
        DB::table('choice_test_answer')->insert(['question_id' => '36','value' => '1','answer' => 'Vision']);
        DB::table('choice_test_answer')->insert(['question_id' => '37','value' => '1','answer' => 'Estetika dan Etika']);
        DB::table('choice_test_answer')->insert(['question_id' => '37','value' => '0','answer' => 'Visual dan Verbal']);
        DB::table('choice_test_answer')->insert(['question_id' => '37','value' => '0','answer' => 'Empati dan Simpati']);
        DB::table('choice_test_answer')->insert(['question_id' => '37','value' => '0','answer' => 'Confidence dan Convenient']);
        DB::table('choice_test_answer')->insert(['question_id' => '38','value' => '0','answer' => 'Kebersihan']);
        DB::table('choice_test_answer')->insert(['question_id' => '38','value' => '0','answer' => 'Kerapihan']);
        DB::table('choice_test_answer')->insert(['question_id' => '38','value' => '1','answer' => 'Kelengkapan']);
        DB::table('choice_test_answer')->insert(['question_id' => '38','value' => '0','answer' => 'Keserasian']);
        DB::table('choice_test_answer')->insert(['question_id' => '39','value' => '0','answer' => 'Cara Duduk']);
        DB::table('choice_test_answer')->insert(['question_id' => '39','value' => '1','answer' => 'Cara tidur']);
        DB::table('choice_test_answer')->insert(['question_id' => '39','value' => '0','answer' => 'Cara Berdiri']);
        DB::table('choice_test_answer')->insert(['question_id' => '39','value' => '0','answer' => 'Cara Berjalan']);
        DB::table('choice_test_answer')->insert(['question_id' => '40','value' => '0','answer' => 'Hubungan antara perusahaan dan pelanggan yang memberikan pemenuhan kebutuhan atau pengalaman yang berdampak terhadap kelangsungan bisnis dan loyalitas pelanggannya']);
        DB::table('choice_test_answer')->insert(['question_id' => '40','value' => '0','answer' => 'Hubungan antar personal yang memberikan pemenuhan kebutuhan atau pengalaman yang berdampak terhadap kelangsungan bisnis dan loyalitas pelanggannya']);
        DB::table('choice_test_answer')->insert(['question_id' => '40','value' => '0','answer' => 'Hubungan antar pelanggan yang memberikan pemenuhan kebutuhan atau pengalaman yang berdampak terhadap kelangsungan bisnis dan loyalitas pelanggannya']);
        DB::table('choice_test_answer')->insert(['question_id' => '40','value' => '1','answer' => 'hubungan timbal balik antara individu maupun kelompok untuk menjalin hubungan pertemanan, diskusi, kerjasama yang diterapkan dalam kehidupan bermasyarakat.']);
        DB::table('choice_test_answer')->insert(['question_id' => '41','value' => '0','answer' => 'Penampilan yang pantas & baik']);
        DB::table('choice_test_answer')->insert(['question_id' => '41','value' => '0','answer' => 'Terlihat antusias & percaya diri']);
        DB::table('choice_test_answer')->insert(['question_id' => '41','value' => '0','answer' => 'Suara jelas terdengar']);
        DB::table('choice_test_answer')->insert(['question_id' => '41','value' => '1','answer' => 'Semua jawaban benar']);
        DB::table('choice_test_answer')->insert(['question_id' => '42','value' => '1','answer' => 'Menunduk malu']);
        DB::table('choice_test_answer')->insert(['question_id' => '42','value' => '0','answer' => 'Rangkum presentasi Anda (maks 3 point utama)']);
        DB::table('choice_test_answer')->insert(['question_id' => '42','value' => '0','answer' => 'Menggunakan kutipan']);
        DB::table('choice_test_answer')->insert(['question_id' => '42','value' => '0','answer' => 'Sampaikan kalimat yang menjadi “call to action”']);
        DB::table('choice_test_answer')->insert(['question_id' => '43','value' => '0','answer' => 'Simple (S) x Optimal (O)']);
        DB::table('choice_test_answer')->insert(['question_id' => '43','value' => '0','answer' => 'Simple (S) x Organize (O)']);
        DB::table('choice_test_answer')->insert(['question_id' => '43','value' => '1','answer' => 'Sederhana (S) x Optimal (O)']);
        DB::table('choice_test_answer')->insert(['question_id' => '43','value' => '0','answer' => 'Tidak ada jawaban yang benar']);
        DB::table('choice_test_answer')->insert(['question_id' => '44','value' => '0','answer' => 'Slide berisi banyak tulisan ']);
        DB::table('choice_test_answer')->insert(['question_id' => '44','value' => '1','answer' => 'Slide yang berisi gambar besar dengan warna kontras dan tulisan dengan latar belakang dengan warna transparan']);
        DB::table('choice_test_answer')->insert(['question_id' => '44','value' => '0','answer' => 'Slide dengan background warna gelap dan tulisan dengan font warna hitam']);
        DB::table('choice_test_answer')->insert(['question_id' => '44','value' => '0','answer' => 'Slide dengan kombinasi gambar dan tulisan yang kecil saja agar tidak mencolok']);
        DB::table('choice_test_answer')->insert(['question_id' => '45','value' => '0','answer' => 'Laptop ']);
        DB::table('choice_test_answer')->insert(['question_id' => '45','value' => '0','answer' => 'Pointer']);
        DB::table('choice_test_answer')->insert(['question_id' => '45','value' => '0','answer' => 'Microphone']);
        DB::table('choice_test_answer')->insert(['question_id' => '45','value' => '1','answer' => 'Semua jawaban benar']);
        DB::table('choice_test_answer')->insert(['question_id' => '46','value' => '0','answer' => 'Penampilan']);
        DB::table('choice_test_answer')->insert(['question_id' => '46','value' => '0','answer' => 'Skill']);
        DB::table('choice_test_answer')->insert(['question_id' => '46','value' => '0','answer' => 'Sikap']);
        DB::table('choice_test_answer')->insert(['question_id' => '46','value' => '1','answer' => 'Semua salah']);
        DB::table('choice_test_answer')->insert(['question_id' => '47','value' => '1','answer' => 'Sikap']);
        DB::table('choice_test_answer')->insert(['question_id' => '47','value' => '0','answer' => 'Penampilan']);
        DB::table('choice_test_answer')->insert(['question_id' => '47','value' => '0','answer' => 'Skill']);
        DB::table('choice_test_answer')->insert(['question_id' => '47','value' => '0','answer' => 'Attention']);
        DB::table('choice_test_answer')->insert(['question_id' => '48','value' => '0','answer' => 'Menggali kebutuhan nasabah secara cermat dan menganalisa profil nasabah ( pekerjaan/usaha/hobby/keluarga/kebiasaan transaksi)']);
        DB::table('choice_test_answer')->insert(['question_id' => '48','value' => '0','answer' => 'Menciptakan kebutuhan nasabah ']);
        DB::table('choice_test_answer')->insert(['question_id' => '48','value' => '0','answer' => 'Menginformasikan produk yang sesuai dengan kebutuhan nasabah berdasarkan hasil menggali informasi/profil nasabah']);
        DB::table('choice_test_answer')->insert(['question_id' => '48','value' => '1','answer' => 'Menginformasikan produk yang sedang menjadi produk champion di cabang']);
        DB::table('choice_test_answer')->insert(['question_id' => '49','value' => '0','answer' => 'Melakukan verifikasi data']);
        DB::table('choice_test_answer')->insert(['question_id' => '49','value' => '0','answer' => 'Meminta kelengkapan transaksi']);
        DB::table('choice_test_answer')->insert(['question_id' => '49','value' => '0','answer' => 'Menjelaskan akar permasalahan ']);
        DB::table('choice_test_answer')->insert(['question_id' => '49','value' => '1','answer' => 'Menunjukkan sikap empati']);
        DB::table('choice_test_answer')->insert(['question_id' => '50','value' => '0','answer' => 'Melakukan kontak mata dan tersenyum']);
        DB::table('choice_test_answer')->insert(['question_id' => '50','value' => '0','answer' => 'Menggunakan nama nasabah']);
        DB::table('choice_test_answer')->insert(['question_id' => '50','value' => '1','answer' => 'Berjabat tangan/mengatupkan kedua tangan didada']);
        DB::table('choice_test_answer')->insert(['question_id' => '50','value' => '0','answer' => 'Fokus terhadap transaksi nasabah']);
    }
}
